import { AsyncPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { HealthService } from '../core/health.service';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [AsyncPipe, MatButtonModule, MatCardModule, MatChipsModule, MatProgressSpinnerModule],
  template: `
    <section class="page">
      <header class="page-header">
        <div>
          <p class="eyebrow">Starter dashboard</p>
          <h1>Welcome</h1>
          <p class="subtitle">This is the default starting point generated by the template.</p>
        </div>
        <a mat-flat-button color="primary" href="/swagger-ui/index.html">API Docs</a>
      </header>

      <div class="card-grid">
        <mat-card appearance="outlined" class="dashboard-card">
          <mat-card-header>
            <mat-card-title>Application status</mat-card-title>
            <mat-card-subtitle>Angular Material + Spring Boot</mat-card-subtitle>
          </mat-card-header>

          <mat-card-content>
            <div class="status-row">
              @if (health$ | async; as health) {
                <mat-chip-set aria-label="Backend status">
                  <mat-chip highlighted>{{ health.status }}</mat-chip>
                </mat-chip-set>
                <span>Backend is reachable.</span>
              } @else {
                <mat-spinner diameter="24" />
                <span>Checking backend...</span>
              }
            </div>
          </mat-card-content>

          <mat-card-actions align="end">
            <a mat-button href="/actuator/health">Actuator</a>
            <a mat-flat-button color="primary" href="/api/health">Health</a>
          </mat-card-actions>
        </mat-card>

        <mat-card appearance="outlined" class="dashboard-card">
          <mat-card-header>
            <mat-card-title>Resources</mat-card-title>
            <mat-card-subtitle>Useful links while you build</mat-card-subtitle>
          </mat-card-header>
          <mat-card-content>
            <ul class="link-list">
              <li><a href="/swagger-ui/index.html">OpenAPI / Swagger UI</a></li>
              <li><a href="/api/health">Backend health endpoint</a></li>
              <li><a href="/actuator/health">Actuator health</a></li>
            </ul>
          </mat-card-content>
        </mat-card>

        <mat-card appearance="outlined" class="dashboard-card">
          <mat-card-header>
            <mat-card-title>Getting started</mat-card-title>
            <mat-card-subtitle>Where to customize this template</mat-card-subtitle>
          </mat-card-header>
          <mat-card-content>
            <ul class="tip-list">
              <li>
                Adjust theme tokens in <code>theme.css</code>, <code>theme.ft.css</code>, and
                <code>theme.gl.css</code>.
              </li>
              <li>Add feature routes under <code>features/</code>.</li>
              <li>Regenerate the API client after backend changes.</li>
            </ul>
          </mat-card-content>
        </mat-card>
      </div>
    </section>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HomeComponent {
  private readonly healthService = inject(HealthService);

  protected readonly health$ = this.healthService.load();
}
