/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  createdAt?: string;
  enabled?: boolean;
  id?: number;
  role?: 'ADMIN' | 'USER';
  username?: string;
}
