/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminOverviewResponse } from '../../models/admin-overview-response';

export interface Overview$Params {
}

export function overview(http: HttpClient, rootUrl: string, params?: Overview$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminOverviewResponse>> {
  const rb = new RequestBuilder(rootUrl, overview.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminOverviewResponse>;
    })
  );
}

overview.PATH = '/api/admin';
