/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThemeResponse } from '../../models/theme-response';

export interface GetTheme$Params {
}

export function getTheme(http: HttpClient, rootUrl: string, params?: GetTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeResponse>> {
  const rb = new RequestBuilder(rootUrl, getTheme.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeResponse>;
    })
  );
}

getTheme.PATH = '/api/settings/theme';
