/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThemeResponse } from '../../models/theme-response';
import { UpdateThemeRequest } from '../../models/update-theme-request';

export interface UpdateTheme$Params {
      body: UpdateThemeRequest
}

export function updateTheme(http: HttpClient, rootUrl: string, params: UpdateTheme$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeResponse>> {
  const rb = new RequestBuilder(rootUrl, updateTheme.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeResponse>;
    })
  );
}

updateTheme.PATH = '/api/admin/settings/theme';
